basePath: /v1
definitions:
  command.CreateUserCommand:
    properties:
      nickname:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  command.PasswordLoginCommand:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  dto.AuthenticationDTO:
    properties:
      token:
        type: string
    type: object
  web.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户注册请求
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/command.CreateUserCommand'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/dto.AuthenticationDTO'
        "409":
          description: Can not find ID
          schema:
            $ref: '#/definitions/web.Error'
      summary: 用户注册
  /users:passwordLogin:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户注册请求
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/command.PasswordLoginCommand'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功返回认证token
          schema:
            $ref: '#/definitions/dto.AuthenticationDTO'
        "401":
          description: 密码输入错误
          schema:
            $ref: '#/definitions/web.Error'
      summary: 账号密码登录
swagger: "2.0"
