basePath: /v1
definitions:
  web.Error:
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users:checkEmail:
    post:
      consumes:
      - application/json
      description: description
      parameters:
      - description: Mobile
        in: body
        name: mobile
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: true已存在,false不存在
          schema:
            type: bool
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/web.Error'
      summary: 校验手机号是否存在
swagger: "2.0"
